in_features: 100
layers:
- 100
- 64
- 32
- 1
n_cvs: 1
n_states: 2
options:
  nn:
    activation: relu
  norm_in: null
  optimizer:
    lr: 0.001
out_features: 1
postprocessing: null
preprocessing: null
target_centers:
- -25
- 25
target_sigmas: !!python/object/apply:numpy.core.multiarray._reconstruct
  args:
  - !!python/name:numpy.ndarray ''
  - !!python/tuple
    - 0
  - !!binary |
    Yg==
  state: !!python/tuple
  - 1
  - !!python/tuple
    - 2
  - !!python/object/apply:numpy.dtype
    args:
    - f8
    - false
    - true
    state: !!python/tuple
    - 3
    - <
    - null
    - null
    - null
    - -1
    - -1
    - 0
  - false
  - !!binary |
    mpmZmZmZyT+amZmZmZnJPw==
